/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-08-11 14:38:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidad.Usuario;
import entidad.Cargo;
import entidad.DashboardSemanaCliente;
import entidad.DashboardSemanaPedido;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entidad.DashboardSemanaCliente");
    _jspx_imports_classes.add("entidad.Cargo");
    _jspx_imports_classes.add("entidad.Usuario");
    _jspx_imports_classes.add("entidad.DashboardSemanaPedido");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Dashboard</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css'\n");
      out.write("	rel='stylesheet'>\n");
      out.write("<link href='css/estilos.css' rel='stylesheet'>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

	Usuario usuario = (Usuario) session.getAttribute("usuario");
	if (usuario != null) {
	
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"sidebar close\">\n");
      out.write("		<div class=\"logo-details\">\n");
      out.write("			<i class='bx bxl-product-hunt'></i> <span class=\"logo_name\">ProyectoLP</span>\n");
      out.write("		</div>\n");
      out.write("		<ul class=\"nav-links\">\n");
      out.write("			<li><a href=\"servletdashboa\"> <i class='bx bx-grid-alt'></i>\n");
      out.write("					<span class=\"link_name\">Dashboard</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\" href=\"servletdashboa\">Dashboard</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletUsuar?ejecutar=listar&incial=\"> <i\n");
      out.write("					class='bx bxs-user'></i><span class=\"link_name\"> Usuarios</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletUsuar?ejecutar=listar&incial=\">Usuarios</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletclient?ejecutarClientes=listar&incial=\">\n");
      out.write("					<i class='bx bxs-group'></i><span class=\"link_name\">Clientes</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletclient?ejecutarClientes=listar&incial=\">Clientes</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletProduct?ejecutar=listar&incial=\"> <i\n");
      out.write("					class='bx bx-archive'></i> <span class=\"link_name\">Productos</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletProduct?ejecutar=listar&incial=\">Productos</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletUsuar?ejecutar=listarInactivos\"> <i\n");
      out.write("					class='bx bxs-error-circle'></i> <span class=\"link_name\">Inactivos</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletUsuar?ejecutar=listarInactivos\">Inactivos</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletpedido?ejecutar=listarNuevo\"> <i\n");
      out.write("					class='bx bx-cart-alt'></i> <span class=\"link_name\"> Pedidos</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\" href=\"servletpedido?ejecutar=listarNuevo\">\n");
      out.write("							Pedidos</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletpedido?ejecutar=listadoPedido&incial=\"> <i class='bx bxs-report'></i> <span class=\"link_name\"> Reportes</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\" href=\"servletpedido?ejecutar=listadoPedido&incial=\">\n");
      out.write("							Reportes</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li>\n");
      out.write("				<div class=\"profile-details\">\n");
      out.write("					<div class=\"profile-content\">\n");
      out.write("						<img src=\"image/usuario.png\" alt=\"profileImg\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"name-job\">\n");
      out.write("						<div class=\"profile_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.getNombre()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("						<div class=\"job\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.getCargo().getNombreCargo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("					</div>\n");
      out.write("					<form action=\"cerrarsesion\" method=\"POST\">\n");
      out.write("						<a href=\"cerrarsesion\"><i class='bx bx-log-out'></i></a>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("	<section class=\"home-section\">\n");
      out.write("		<div class=\"home-content\">\n");
      out.write("			<i class='bx bx-menu'></i> <span class=\"text\">Bienvenido :\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.getNombre()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"m-4\">\n");
      out.write("			<div class=\"d-flex gap-5 mb-4\">\n");
      out.write("				<div class=\"card col\" style=\"width: 18rem;\">\n");
      out.write("					<div class=\"card-header text-center\">Usuarios</div>\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<div\n");
      out.write("							class=\"d-flex gap-5 justify-content-center align-items-center\">\n");
      out.write("							<div>\n");
      out.write("								<img alt=\"\" src=\"image/programador.png\" width=\"100\" height=\"100\">\n");
      out.write("							</div>\n");
      out.write("							<div>\n");
      out.write("								<div class=\"row-inline gap-2\">\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-3 text-body-secondary\">\n");
      out.write("											Registrados hoy dia: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getHoyUsuario()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-3 text-body-secondary\">\n");
      out.write("											Inactivos: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getUsuarioInactivos()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-2 text-body-secondary\">\n");
      out.write("											Total: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getUsuarioTotal()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"card col\" style=\"width: 18rem;\">\n");
      out.write("					<div class=\"card-header text-center\">Clientes</div>\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<div\n");
      out.write("							class=\"d-flex gap-5 justify-content-center align-items-center\">\n");
      out.write("							<div>\n");
      out.write("								<img alt=\"\" src=\"image/kyc.png\" width=\"100\" height=\"100\">\n");
      out.write("							</div>\n");
      out.write("							<div>\n");
      out.write("								<div class=\"row-inline gap-2\">\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-3 text-body-secondary\">\n");
      out.write("											Registrados hoy dia: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getClienteHoy()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-3 text-body-secondary\">\n");
      out.write("											Inactivos: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getClienteInactivos()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-2 text-body-secondary\">\n");
      out.write("											Total: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getClienteTotal()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"card col\" style=\"width: 18rem;\">\n");
      out.write("					<div class=\"card-header text-center\">Productos</div>\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<div\n");
      out.write("							class=\"d-flex gap-5 justify-content-center align-items-center\">\n");
      out.write("							<div>\n");
      out.write("								<img alt=\"\" src=\"image/productos.png\" width=\"100\" height=\"100\">\n");
      out.write("							</div>\n");
      out.write("							<div>\n");
      out.write("								<div class=\"row-inline gap-2\">\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-3 text-body-secondary\">\n");
      out.write("											Registrados hoy dia: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getHoyproductos()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-3 text-body-secondary\">\n");
      out.write("											Inactivos: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getProductosInactivos()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col\">\n");
      out.write("										<h6 class=\"card-subtitle mb-2 text-body-secondary\">\n");
      out.write("											Total: <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dash.getProductosTotal()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("										</h6>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"d-flex gap-5\">\n");
      out.write("				<div class=\"card col-8\">\n");
      out.write("					<div class=\"card-header\">Ventas Realizadas esta Semana</div>\n");
      out.write("					<div class=\"card-body\" style=\"height: 600px\">\n");
      out.write("						<canvas id=\"chart1\"></canvas>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"card col\">\n");
      out.write("					<div class=\"card-header\">Clientes Registrados esta Semana</div>\n");
      out.write("					<div class=\"card-body\" style=\"height: 600px\">\n");
      out.write("						<canvas id=\"chart2\"></canvas>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</section>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		// Configuración del primer gráfico\n");
      out.write("		var ctx1 = document.getElementById('chart1').getContext('2d');\n");
      out.write("		var chart1 = new Chart(ctx1, {\n");
      out.write("			type: 'bar',\n");
      out.write("			data: {\n");
      out.write("				labels: ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Dominingo'],\n");
      out.write("				");

				DashboardSemanaPedido semaPedi = (DashboardSemanaPedido) request.getAttribute("semanPedi");
			 	
      out.write("\n");
      out.write("				datasets: [{\n");
      out.write("					label: 'Ventas',\n");
      out.write("					data: [");
      out.print(semaPedi.lunes);
      out.write(',');
      out.write(' ');
      out.print(semaPedi.martes);
      out.write(',');
      out.write(' ');
      out.print(semaPedi.mier);
      out.write(',');
      out.write(' ');
      out.print(semaPedi.jueve);
      out.write(',');
      out.print(semaPedi.vierne);
      out.write(',');
      out.write(' ');
      out.print(semaPedi.sabado);
      out.write(',');
      out.write(' ');
      out.print(semaPedi.domin);
      out.write("],\n");
      out.write("					backgroundColor: 'rgba(75, 192, 192, 0.6)',\n");
      out.write("					borderColor: 'rgba(75, 192, 192, 1)',\n");
      out.write("					borderWidth: 1\n");
      out.write("				}]\n");
      out.write("			},\n");
      out.write("			options: {\n");
      out.write("				scales: {\n");
      out.write("					y: {\n");
      out.write("						beginAtZero: true\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		// Configuración del segundo gráfico\n");
      out.write("		var ctx2 = document.getElementById('chart2').getContext('2d');\n");
      out.write("		var chart2 = new Chart(ctx2, {\n");
      out.write("			 type: 'pie',\n");
      out.write("			 data: {\n");
      out.write("				  labels: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],\n");
      out.write("				  ");

					DashboardSemanaCliente sema = (DashboardSemanaCliente) request.getAttribute("seman");
				  
      out.write("\n");
      out.write("				  datasets: [{\n");
      out.write("				    label: 'Clientes',\n");
      out.write("				    data: [");
      out.print(sema.lunes);
      out.write(',');
      out.write(' ');
      out.print(sema.martes);
      out.write(',');
      out.write(' ');
      out.print(sema.mier);
      out.write(',');
      out.write(' ');
      out.print(sema.jueve);
      out.write(',');
      out.print(sema.vierne);
      out.write(',');
      out.write(' ');
      out.print(sema.sabado);
      out.write(',');
      out.write(' ');
      out.print(sema.domin);
      out.write("],\n");
      out.write("				    backgroundColor: [\n");
      out.write("				      'rgb(255, 99, 132)',\n");
      out.write("				      'rgb(54, 162, 235)',\n");
      out.write("				      'rgb(255, 205, 89)',\n");
      out.write("				      'rgb(75, 192, 192)',\n");
      out.write("				      'rgb(255, 159, 64)',\n");
      out.write("				      'rgb(153, 102, 255)',\n");
      out.write("				      'rgb(0, 128, 0)'\n");
      out.write("				    ],\n");
      out.write("				    cutout: 1,\n");
      out.write("				    hoverOffset: 4\n");
      out.write("				  }]\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<script src=\"js/script.js\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	");

	} else {
	request.getRequestDispatcher("index.jsp").forward(request, response);
	}

	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
	response.setHeader("Pragma", "no-cache");
	response.setHeader("Expires", "0");
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
