/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-08-11 14:38:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"/assets/logo-vt.svg\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Iniciar Sesión</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"alerta/alertify.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"alerta/themes/default.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"d-flex flex-column\"\r\n");
      out.write("			style=\"display: flex; align-items: center; justify-content: center; height: 963px\">\r\n");
      out.write("			<div style=\"padding-bottom: 15px; text-align: center\">\r\n");
      out.write("				<h1 class=\"text-dark fw-bold fs-12\" style=\"margin-bottom: 0px;\">Iniciar\r\n");
      out.write("					Sesión</h1>\r\n");
      out.write("				<p class=\"text-dark\">Llené el formulario para Iniciar Sesion</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"width: 440px; height: 270px; padding: 20px\"\r\n");
      out.write("				class=\"shadow rounded-4\">\r\n");
      out.write("				<form action=\"validar\" id=\"id_form\" method=\"POST\"\r\n");
      out.write("					class=\"needs-validation\" novalidate>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"formGroupExampleInput\" class=\"form-label\">Usuario</label>\r\n");
      out.write("						<input class=\"form-control\" type=\"text\" id=\"id_usuario\"\r\n");
      out.write("							name=\"usua\" placeholder=\"Ingresa su nombre de usuario\" value=\"jack_username\"\r\n");
      out.write("							required=\"required\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"formGroupExampleInput\" class=\"form-label\">Contraseña</label>\r\n");
      out.write("						<input class=\"form-control\" type=\"password\" id=\"id_contraseña\" value=\"jack_password\"\r\n");
      out.write("							name=\"contra\" placeholder=\"Ingrese su contraseña\"\r\n");
      out.write("							required=\"required\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<input type=\"submit\" value=\"Ingresar\" class=\"btn w-100\"\r\n");
      out.write("							style=\"background-color: #1d1b31; color: white;\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	String mensaje = (String) request.getSession().getAttribute("MENSAJE");
	String tipo = (String) request.getSession().getAttribute("TIPO");
	if (mensaje != null) {
	
      out.write("\r\n");
      out.write("	<div class=\"alertify-notifier ajs-bottom ajs-right\">\r\n");
      out.write("		<div id=\"alert\" class=\"ajs-message ");
      out.print(tipo);
      out.write('"');
      out.write('>');
      out.print(mensaje);
      out.write("</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("			$(document).ready(function() {\r\n");
      out.write("				var successAlert = document.getElementById(\"alert\");\r\n");
      out.write("	            successAlert.classList.add(\"ajs-visible\");\r\n");
      out.write("	            setTimeout(function () {\r\n");
      out.write("	                successAlert.classList.remove(\"ajs-visible\");\r\n");
      out.write("	            }, 3000);\r\n");
      out.write("			});\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("	");

	}
	request.getSession().removeAttribute("MENSAJE");
	request.getSession().removeAttribute("TIPO");
	
      out.write("\r\n");
      out.write("	<script src=\"alerta/alertify.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	(() => {\r\n");
      out.write("		  'use strict'\r\n");
      out.write("		  const forms = document.querySelectorAll('.needs-validation')\r\n");
      out.write("		  Array.from(forms).forEach(form => {\r\n");
      out.write("		    form.addEventListener('submit', event => {\r\n");
      out.write("		      if (!form.checkValidity()) {\r\n");
      out.write("		        event.preventDefault()\r\n");
      out.write("		        event.stopPropagation()\r\n");
      out.write("		      }\r\n");
      out.write("\r\n");
      out.write("		      form.classList.add('was-validated')\r\n");
      out.write("		    }, false)\r\n");
      out.write("		  })\r\n");
      out.write("		})()\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
