/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-08-28 07:45:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidad.Usuario;
import entidad.Cargo;

public final class ListarPedidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Jack%20Moreno/Documents/Java/001_ProyectoJava/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Proyect/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691764601686L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entidad.Cargo");
    _jspx_imports_classes.add("entidad.Usuario");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Registrar Pedidos</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.css\">\n");
      out.write("<!-- Boxiocns CDN Link -->\n");
      out.write("<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css'\n");
      out.write("	rel='stylesheet'>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"alerta/alertify.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"alerta/themes/default.css\">\n");
      out.write("<style>\n");
      out.write(".table-input {\n");
      out.write("	border: none;\n");
      out.write("	background-color: transparent;\n");
      out.write("	box-shadow: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-input:focus {\n");
      out.write("	outline: none;\n");
      out.write("	box-shadow: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".formu {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".center-input {\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

	Usuario usuario = (Usuario) session.getAttribute("usuario");
	if (usuario != null) {
	
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"sidebar close\">\n");
      out.write("		<div class=\"logo-details\">\n");
      out.write("			<i class='bx bxl-product-hunt'></i> <span class=\"logo_name\">ProyectoLP</span>\n");
      out.write("		</div>\n");
      out.write("		<ul class=\"nav-links\">\n");
      out.write("			<li><a href=\"servletdashboa\"> <i class='bx bx-grid-alt'></i>\n");
      out.write("					<span class=\"link_name\">Dashboard</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\" href=\"servletdashboa\">Dashboard</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletUsuar?ejecutar=listar&incial=\"> <i\n");
      out.write("					class='bx bxs-user'></i><span class=\"link_name\"> Usuarios</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletUsuar?ejecutar=listar&incial=\">Usuarios</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletclient?ejecutarClientes=listar&incial=\">\n");
      out.write("					<i class='bx bxs-group'></i><span class=\"link_name\">Clientes</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletclient?ejecutarClientes=listar&incial=\">Clientes</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletProduct?ejecutar=listar&incial=\"> <i\n");
      out.write("					class='bx bx-archive'></i> <span class=\"link_name\">Productos</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletProduct?ejecutar=listar&incial=\">Productos</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletUsuar?ejecutar=listarInactivos\"> <i\n");
      out.write("					class='bx bxs-error-circle'></i> <span class=\"link_name\">Inactivos</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletUsuar?ejecutar=listarInactivos\">Inactivos</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletpedido?ejecutar=listarNuevo\"> <i\n");
      out.write("					class='bx bx-cart-alt'></i> <span class=\"link_name\"> Pedidos</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\"\n");
      out.write("						href=\"servletpedido?ejecutar=listarNuevo\"> Pedidos</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li><a href=\"servletpedido?ejecutar=listadoPedido&incial=\"> <i class='bx bxs-report'></i>\n");
      out.write("					<span class=\"link_name\"> Reportes</span>\n");
      out.write("			</a>\n");
      out.write("				<ul class=\"sub-menu blank\">\n");
      out.write("					<li><a class=\"link_name\" href=\"servletpedido?ejecutar=listadoPedido&incial=\">\n");
      out.write("							Reportes</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("			<li>\n");
      out.write("				<div class=\"profile-details\">\n");
      out.write("					<div class=\"profile-content\">\n");
      out.write("						<img src=\"image/usuario.png\" alt=\"profileImg\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"name-job\">\n");
      out.write("						<div class=\"profile_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.getNombre()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("						<div class=\"job\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.getCargo().getNombreCargo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("					</div>\n");
      out.write("					<form action=\"cerrarsesion\" method=\"POST\">\n");
      out.write("						<a href=\"cerrarsesion\"><i class='bx bx-log-out'></i></a>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("	<section class=\"home-section\">\n");
      out.write("		<div class=\"home-content\">\n");
      out.write("			<i class='bx bx-menu'></i> <span class=\"text\">Bienvenido :\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.getNombre()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"m-4\" style=\"height: 500px;\">\n");
      out.write("			<div class=\"row mb-3\">\n");
      out.write("				<div class=\"col\">\n");
      out.write("					<a href=\"servletpedido?ejecutar=listar\" class=\"btn btn-warning\">Agregar</a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col\">\n");
      out.write("					<form class=\"input-group\" action=\"servletpedido\">\n");
      out.write("					<input type=\"hidden\" name=\"ejecutar\" value=\"listadoPedido\">\n");
      out.write("						<span class=\"input-group-text\" id=\"inputGroup-sizing-default\">Buscar</span>\n");
      out.write("						<input type=\"text\" class=\"form-control\"\n");
      out.write("							aria-label=\"Sizing example input\"\n");
      out.write("							aria-describedby=\"inputGroup-sizing-default\"\n");
      out.write("							placeholder=\"Ingrese el nombre del usuario\" name=\"incial\">\n");
      out.write("\n");
      out.write("						<button type=\"submit\" href=\"\" class=\"btn btn-secondary\">\n");
      out.write("							<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\n");
      out.write("								fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\n");
      out.write("				<path\n");
      out.write("									d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\" />\n");
      out.write("  				</svg>\n");
      out.write("						</button>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<table id=\"tablaProductos\" class=\"table table-striped table-bordered\">\n");
      out.write("				<thead>\n");
      out.write("					<tr>\n");
      out.write("						<th>ID Pedido</th>\n");
      out.write("						<th>Nombre del Cliente</th>\n");
      out.write("						<th>Empleado</th>\n");
      out.write("						<th>Monto</th>\n");
      out.write("						<th>Fecha</th>\n");
      out.write("						<th>Estado</th>\n");
      out.write("						<th></th>\n");
      out.write("					</tr>\n");
      out.write("				</thead>\n");
      out.write("				<tbody>\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				</tbody>\n");
      out.write("			</table>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	\n");
      out.write("	<!-- Modal Cancelar-->\n");
      out.write("		<div class=\"modal fade\" id=\"cancelaPedido\" tabindex=\"-1\"\n");
      out.write("			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Cancelar \n");
      out.write("							Pedido</h1>\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("							aria-label=\"Close\"></button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<form action=\"servletpedido\">\n");
      out.write("							<input type=\"hidden\" name=\"ejecutar\" value=\"cancelarPedido\"> <label\n");
      out.write("								for=\"formGroupExampleInput\" class=\"form-label mb-3\">¿Deseas\n");
      out.write("								cancelar este pedido?</label> \n");
      out.write("								<input type=\"hidden\" type=\"text\" id=\"codpedidoCancel\" name=\"codpedidoCancel\">\n");
      out.write("								<input type=\"hidden\" type=\"text\" id=\"estapedidoCancel\" name=\"estapedidoCancel\">\n");
      out.write("							<div class=\"modal-footer\">\n");
      out.write("								<button type=\"submit\" class=\"btn btn-danger\">Cancelar</button>\n");
      out.write("								<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("									data-bs-dismiss=\"modal\">Cerrar</button>\n");
      out.write("							</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<!-- Modal Finalizar-->\n");
      out.write("		<div class=\"modal fade\" id=\"finalizarPedido\" tabindex=\"-1\"\n");
      out.write("			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Finalizar \n");
      out.write("							Pedido</h1>\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("							aria-label=\"Close\"></button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<form action=\"servletpedido\">\n");
      out.write("							<input type=\"hidden\" name=\"ejecutar\" value=\"finalizarPedido\"> <label\n");
      out.write("								for=\"formGroupExampleInput\" class=\"form-label mb-3\">¿Deseas\n");
      out.write("								finalizar este pedido?</label> \n");
      out.write("								<input type=\"hidden\" type=\"text\" id=\"codPedidoFina\" name=\"codPedidoFina\">\n");
      out.write("								<input type=\"hidden\" type=\"text\" id=\"estapedidofin\" name=\"estapedidofin\">\n");
      out.write("							<div class=\"modal-footer\">\n");
      out.write("								<button type=\"submit\" class=\"btn btn-success\">Aceptar</button>\n");
      out.write("								<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("									data-bs-dismiss=\"modal\">Cerrar</button>\n");
      out.write("							</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	\n");
      out.write("	");

	String mensaje = (String) request.getSession().getAttribute("MENSAJE");
	String tipo = (String) request.getSession().getAttribute("TIPO");
	if (mensaje != null) {
	
      out.write("\n");
      out.write("	<div class=\"alertify-notifier ajs-bottom ajs-right\">\n");
      out.write("		<div id=\"alert\" class=\"ajs-message ");
      out.print(tipo);
      out.write('"');
      out.write('>');
      out.print(mensaje);
      out.write("</div>\n");
      out.write("	</div>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("	<script>\n");
      out.write("			$(document).ready(function() {\n");
      out.write("				var successAlert = document.getElementById(\"alert\");\n");
      out.write("	            successAlert.classList.add(\"ajs-visible\");\n");
      out.write("	            setTimeout(function () {\n");
      out.write("	                successAlert.classList.remove(\"ajs-visible\");\n");
      out.write("	            }, 3000);\n");
      out.write("			});\n");
      out.write("		</script>\n");
      out.write("	");

	}
	request.getSession().removeAttribute("MENSAJE");
	request.getSession().removeAttribute("TIPO");
	
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"alerta/alertify.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		function cancelarPedid(id, estado){\n");
      out.write("			var codigoPedioCanc = document.getElementById('codpedidoCancel');\n");
      out.write("			var estadoPediCan = document.getElementById('estapedidoCancel');\n");
      out.write("			codigoPedioCanc.value = id;\n");
      out.write("			if(estado == \"CANCELADO\"){\n");
      out.write("				estadoPediCan.value=2;\n");
      out.write("			}else if(estado == \"FINALIZADO\"){\n");
      out.write("				estadoPediCan.value=3;\n");
      out.write("			}else{\n");
      out.write("				estadoPediCan.value=1;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var modal = new bootstrap.Modal(document.getElementById('cancelaPedido'));\n");
      out.write("			modal.show();\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function finalizarPed(id, estado){\n");
      out.write("			var codigoFina = document.getElementById('codPedidoFina');\n");
      out.write("			var estadoFina = document.getElementById('estapedidofin');\n");
      out.write("			codigoFina.value = id;\n");
      out.write("			if(estado == \"CANCELADO\"){\n");
      out.write("				estadoFina.value=2;\n");
      out.write("			}else if(estado == \"FINALIZADO\"){\n");
      out.write("				estadoFina.value=3;\n");
      out.write("			}else{\n");
      out.write("				estadoFina.value=1;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var modal = new bootstrap.Modal(document.getElementById('finalizarPedido'));\n");
      out.write("			modal.show();\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("	<script src=\"js/detalleVenta.js\"></script>\n");
      out.write("	<script src=\"jquery/jquery-3.3.1.min.js\"></script>\n");
      out.write("	<script src=\"popper/popper.min.js\"></script>\n");
      out.write("	<script src=\"bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("	<script src=\"datatables/Buttons-1.5.6/js/dataTables.buttons.min.js\"></script>\n");
      out.write("	<script src=\"datatables/JSZip-2.5.0/jszip.min.js\"></script>\n");
      out.write("	<script src=\"datatables/pdfmake-0.1.36/pdfmake.min.js\"></script>\n");
      out.write("	<script src=\"datatables/pdfmake-0.1.36/vfs_fonts.js\"></script>\n");
      out.write("	<script src=\"datatables/Buttons-1.5.6/js/buttons.html5.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"datatables/datatables.min.js\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"\n");
      out.write("		integrity=\"sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script>\n");
      out.write("		$(document)\n");
      out.write("				.ready(\n");
      out.write("						function() {\n");
      out.write("							$('#tablaProductos')\n");
      out.write("									.DataTable(\n");
      out.write("											{\n");
      out.write("												searching : false,\n");
      out.write("												lengthChange : false,\n");
      out.write("												language : {\n");
      out.write("													\"decimal\" : \"\",\n");
      out.write("													\"emptyTable\" : \"No hay datos disponibles en la tabla\",\n");
      out.write("													\"info\" : \"Mostrando _START_ a _END_ de _TOTAL_ registros\",\n");
      out.write("													\"infoEmpty\" : \"Mostrando 0 a 0 de 0 registros\",\n");
      out.write("													\"infoFiltered\" : \"(filtrados de _MAX_ registros totales)\",\n");
      out.write("													\"infoPostFix\" : \"\",\n");
      out.write("													\"thousands\" : \",\",\n");
      out.write("													/*\"lengthMenu\": \"Mostrar _MENU_ registros por página\",*/\n");
      out.write("													\"loadingRecords\" : \"Cargando...\",\n");
      out.write("													\"processing\" : \"Procesando...\",\n");
      out.write("													\"search\" : \"Buscar:\",\n");
      out.write("													\"zeroRecords\" : \"No se encontraron registros coincidentes\",\n");
      out.write("													\"paginate\" : {\n");
      out.write("														\"first\" : \"Primero\",\n");
      out.write("														\"last\" : \"Último\",\n");
      out.write("														\"next\" : \"Siguiente\",\n");
      out.write("														\"previous\" : \"Anterior\"\n");
      out.write("													},\n");
      out.write("													\"aria\" : {\n");
      out.write("														\"sortAscending\" : \": activar para ordenar la columna ascendente\",\n");
      out.write("														\"sortDescending\" : \": activar para ordenar la columna descendente\"\n");
      out.write("													}\n");
      out.write("												}\n");
      out.write("											});\n");
      out.write("						});\n");
      out.write("		$(document)\n");
      out.write("				.ready(\n");
      out.write("						function() {\n");
      out.write("							$('#tableProductos')\n");
      out.write("									.DataTable(\n");
      out.write("											{\n");
      out.write("												lengthChange : false,\n");
      out.write("												language : {\n");
      out.write("													\"decimal\" : \"\",\n");
      out.write("													\"emptyTable\" : \"No hay datos disponibles en la tabla\",\n");
      out.write("													\"info\" : \"Mostrando _START_ a _END_ de _TOTAL_ registros\",\n");
      out.write("													\"infoEmpty\" : \"Mostrando 0 a 0 de 0 registros\",\n");
      out.write("													\"infoFiltered\" : \"(filtrados de _MAX_ registros totales)\",\n");
      out.write("													\"infoPostFix\" : \"\",\n");
      out.write("													\"thousands\" : \",\",\n");
      out.write("													/*\"lengthMenu\": \"Mostrar _MENU_ registros por página\",*/\n");
      out.write("													\"loadingRecords\" : \"Cargando...\",\n");
      out.write("													\"processing\" : \"Procesando...\",\n");
      out.write("													\"search\" : \"Buscar:\",\n");
      out.write("													\"zeroRecords\" : \"No se encontraron registros coincidentes\",\n");
      out.write("													\"paginate\" : {\n");
      out.write("														\"first\" : \"Primero\",\n");
      out.write("														\"last\" : \"Último\",\n");
      out.write("														\"next\" : \"Siguiente\",\n");
      out.write("														\"previous\" : \"Anterior\"\n");
      out.write("													},\n");
      out.write("													\"aria\" : {\n");
      out.write("														\"sortAscending\" : \": activar para ordenar la columna ascendente\",\n");
      out.write("														\"sortDescending\" : \": activar para ordenar la columna descendente\"\n");
      out.write("													}\n");
      out.write("												}\n");
      out.write("											});\n");
      out.write("						});\n");
      out.write("		$(document)\n");
      out.write("				.ready(\n");
      out.write("						function() {\n");
      out.write("							$('#tableClientes')\n");
      out.write("									.DataTable(\n");
      out.write("											{\n");
      out.write("												lengthChange : false,\n");
      out.write("												language : {\n");
      out.write("													\"decimal\" : \"\",\n");
      out.write("													\"emptyTable\" : \"No hay datos disponibles en la tabla\",\n");
      out.write("													\"info\" : \"Mostrando _START_ a _END_ de _TOTAL_ registros\",\n");
      out.write("													\"infoEmpty\" : \"Mostrando 0 a 0 de 0 registros\",\n");
      out.write("													\"infoFiltered\" : \"(filtrados de _MAX_ registros totales)\",\n");
      out.write("													\"infoPostFix\" : \"\",\n");
      out.write("													\"thousands\" : \",\",\n");
      out.write("													/*\"lengthMenu\": \"Mostrar _MENU_ registros por página\",*/\n");
      out.write("													\"loadingRecords\" : \"Cargando...\",\n");
      out.write("													\"processing\" : \"Procesando...\",\n");
      out.write("													\"search\" : \"Buscar:\",\n");
      out.write("													\"zeroRecords\" : \"No se encontraron registros coincidentes\",\n");
      out.write("													\"paginate\" : {\n");
      out.write("														\"first\" : \"Primero\",\n");
      out.write("														\"last\" : \"Último\",\n");
      out.write("														\"next\" : \"Siguiente\",\n");
      out.write("														\"previous\" : \"Anterior\"\n");
      out.write("													},\n");
      out.write("													\"aria\" : {\n");
      out.write("														\"sortAscending\" : \": activar para ordenar la columna ascendente\",\n");
      out.write("														\"sortDescending\" : \": activar para ordenar la columna descendente\"\n");
      out.write("													}\n");
      out.write("												}\n");
      out.write("											});\n");
      out.write("						});\n");
      out.write("	</script>\n");
      out.write("	<script src=\"js/script.js\"></script>\n");
      out.write("	");

	} else {
	request.getRequestDispatcher("index.jsp").forward(request, response);
	}

	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
	response.setHeader("Pragma", "no-cache");
	response.setHeader("Expires", "0");
	
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /ListarPedidos.jsp(162,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listaPed}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /ListarPedidos.jsp(162,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("x");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("						<tr>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.codPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.cliente.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.cliente.apellidos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.usuario.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.usuario.apellidos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.monto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.fecha}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td class=\" fw-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td style=\"text-align: center;\">\n");
            out.write("								<button class=\"btn btn-success\" onclick=\"finalizarPed('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.codPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">Finalizar</button>\n");
            out.write("								<button class=\"btn btn-danger\" onclick=\"cancelarPedid('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.codPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("', '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.estado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">Cancelar</button>\n");
            out.write("								<a class=\"btn btn-secondary\" href=\"servletpedido?ejecutar=generarReporte&codigo=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x.codPedido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" target=\"_blank\">Boleta</a>\n");
            out.write("							</td>\n");
            out.write("						</tr>\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
