CREATE DATABASE  IF NOT EXISTS PROYECTO_LP1;
USE PROYECTO_LP1;

DROP TABLE IF EXISTS CARGO;
CREATE TABLE CARGO 
(
COD_CARGO INT AUTO_INCREMENT PRIMARY KEY,
DESC_CARGO VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO
(
  COD_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRES VARCHAR(25) NOT NULL,
  APELLIDOS VARCHAR(25) NULL,
  TELEFONO VARCHAR(15) NULL,
  CORREO VARCHAR(60) NULL,
  NOMBRE_USUARIO VARCHAR(25) NOT NULL,
  CONTRASENA NVARCHAR(25) NOT NULL,
  COD_CARGO INT,
  ACTIVO BIT(1) NOT NULL,
  FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (COD_CARGO) REFERENCES CARGO(COD_CARGO)
);

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE
(
  COD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRES VARCHAR(50) NOT NULL,
  APELLIDOS VARCHAR(50) NOT NULL,
  DNI VARCHAR(9) NOT NULL,
  TELEFONO VARCHAR(15) NOT NULL,
  CORREO VARCHAR(100),
  DIRECCION VARCHAR(100) NULL,
  FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE CLIENTE
ADD UNIQUE (DNI);

DROP TABLE IF EXISTS CATEGORIA;
CREATE TABLE CATEGORIA 
(
COD_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(60) NOT NULL
);

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS(
COD_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
COD_CATEGORIA INT,
NOMBRE_PRODUCTO VARCHAR(60) NOT NULL,
STOCK INT NOT NULL,
FECHA_VENCIMIENTO DATE NULL,
PRECIO DOUBLE NOT NULL,
ACTIVO BIT(1) NOT NULL,
FECHAREGISTRO DATE DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA)
);

DROP TABLE IF EXISTS ESTADO;
CREATE TABLE ESTADO
(
COD_ESTADO CHAR(3) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PEDIDOS;
CREATE TABLE PEDIDOS
(
COD_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
COD_CLIENTE INT NOT NULL,
COD_USUARIO INT NULL,
FECHA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MONTO DOUBLE NOT NULL,
COD_ESTADO CHAR(3) NOT NULL,
FOREIGN KEY (COD_ESTADO) REFERENCES ESTADO(COD_ESTADO),
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO)
);

DROP TABLE IF EXISTS DETALLE_PEDIDO;
CREATE TABLE DETALLE_PEDIDO
(
COD_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
COD_PEDIDO INT,
COD_PRODUCTO INT,
CANTIDAD INT NOT NULL,
PRECIO_VENTA DOUBLE NOT NULL,
FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDOS(COD_PEDIDO),
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO)
);